# Generated by Django 4.2.3 on 2023-10-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyphen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_head_title', models.CharField(max_length=255)),
                ('product_sub_title', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=2000)),
                ('product_ingredient', models.CharField(max_length=1000)),
                ('product_use', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='hyphen.product')),
            ],
        ),
    ]
