# Generated by Django 4.2.3 on 2023-10-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyphen', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ingredient',
            field=models.CharField(max_length=2000),
        ),
    ]
