# Generated by Django 4.2.3 on 2023-10-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyphen', '0004_product_product_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
