# Generated by Django 4.2.8 on 2024-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hyphen", "0005_product_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_how_does",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_what_does",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_what_it",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
