# Generated by Django 4.2.8 on 2024-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hyphen", "0006_product_product_how_does_product_product_what_does_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_how_use",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_when_use",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
