# Generated by Django 4.2.8 on 2024-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hyphen", "0007_product_product_how_use_product_product_when_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_main_img",
            field=models.ImageField(blank=True, null=True, upload_to="hyphen/"),
        ),
    ]
